#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Microarray-GeneXplorer
version:      0.1
version_from: VERSION
installdirs:  site
requires:
    GD:                            1.19
    Getopt::Long:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
